### ISSUE TITLE
[request] use OpenCV 3 to get a solution for search images with transparency

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliNG#7]

**Comment by RaiMan** [comment]
no, it is still 2.4.12 (you can see that with the opencv_java2412 dynamic library)

I guess 3.0 I will only use next year.

Any advantages you know about?

**Comment by techtonik** [comment]
https://stackoverflow.com/questions/4761940/opencv-template-matching-and-transparency

This is badly needed - matching image with alpha channel.

**Comment by RaiMan** [comment]
Thanks for the pointer:
apparently OpenCV 3 has an option in matchTemplate() to mask the searched image.
I will check that during the next weeks.

**Comment by ubershy** [comment]
I would really love to be able to search png images with transparency.

**Comment by RaiMan** [comment]
I hope we will see it with version 2

**Comment by techtonik** [comment]
Maybe create a milestone to see what is left until version 2 https://github.com/RaiMan/SikuliX2/milestones ?

**Comment by RaiMan** [comment]
@techtonik 
Hi Anatoly ;-) nice idea: milestones, but ...

> what is left until version 2

... simply said: time :-(
I am a "little" bit behind my plans (private priorities) and currently I only can say:
A somehow basically useable version 2 should be available towards end of this year.
... but transparency awareness will surely not be available then.

Nevertheless, thank you all for loving SikuliX.

**Comment by techtonik** [comment]
As much as I love SikuliX I still have to admin that I don't use it. When I filled this issue almost a year ago, I needed to watch for non-square object on random background and failed to do this though SikuliX. So I started to use Python bindings with OpenCV, but with no progress either. But at least we've managed to package Windows binaries for https://github.com/skvark/opencv-python/ that simply work out of the box.

Maybe rolling release is a better strategy for SikuliX2 as well? Maybe there are people who have more time on their hands and some tasks could be paralleled?

**Comment by RaiMan** [comment]
@techtonik 

Thanks for feedback and information.

> rolling release

... yes, surely the best way in the future.
... but to get something rolling, it first has to have an appropriate shape: this is what I mean with basically useable towards end of this year. Currently it is more something like a big carpet with some more or less loose heaps of code on it: not possible to roll yet ;-)

All the best.

**Comment by CallistoCF** [comment]
Hi Raimund!  My name's Chris, and i wanted to email to say hi, and to thank you so much for Sikuli!!! after trying pretty much every UI testing platform on one of the toughest projects i've ever worked on, I finally tried Sikuli (boss didn't like the idea of images for testing), and i've not only been able to complete my project, but still have no idea what i would have done without it!  (and I'm the third team to work on this problem!).
I was wondering if there's any way i could contribute or help out?  Ive loved using open source tools but haven't contributed as much as i should- i've been sikuli for about two months now, and anything i can do to contribute id be totally interested!  
  I've been letting everyone i know just how awesome the program is- anyhow, thanks again!
Cheers!
Chris

**Comment by Forgen** [comment]
Has anyone hacked a solution using Sikuli to "fake it"? Like if I wanted a square and want to mask out anything within the square.  I'm thinking search for and edge or corner,  the search the region nearby the first match for another corner etc.

**Comment by RaiMan** [comment]
@CallistoCF 
Thanks for kind feedback.

Have a look at the comments above about the development situation:
 - version 1.1.1 still not final
 - version 2 started but not yet in a shape to contribute

as mentioned before: I am a "little" bit behind my plans due to private priorities.

So currently indeed the possibilities to contribute are limited to talk about SikuliX (send me links if you post something), talk about use cases and special solutions, post your findings, requests and ideas here or on launchpad or create pull requests in the doc section.

Nevertheless any pull requests towards 1.1.1 or even 2.0.0 are always welcome.

**Comment by RaiMan** [comment]
@Forgen 
"fake it" does not really make sense, otherwise we would already have a general solution.

Currently your situation (search for something by only looking for the edges and ignore the inner parts of the image (typically buttons with changing content)) can only be done by splitting the image into at least 2 edge images (one for the vertical and one for the horizontal edge) and search for both in a way, that assures that you find a button.
For your private use, you might write a function for that to get a useable feature, but to make such a feature generally useable with all possible options is rather complex.

Even with the masked matchTemplate() (not yet tested) in OpenCV3 the feature in SikuliX is still rather complex, since you need some tool support, to create/define the mask.

Nevertheless: Well, I'll do my very best (as the butler says in "Dinner for One")

**Comment by RaiMan** [comment]
solved in SikuliX version 2.0.0
