### ISSUE TITLE
sikulix2 does not contain IDE UI Class 

### ISSUE THREAD

**Issue by sarkershantonu** [RaiMan/SikuliNG#9]
I was trying to build and try, only API is present. Is there possible to use previous version of Gui(1.1.1)  with New API(2) ?

**Comment by RaiMan** [comment]
use of version 2 is generally not yet supported.
I guess the first nightly builds will not be available before September.
But feel free, to do what you want ;-)

**Comment by vyau** [comment]
In the same thread, I like to ask a question.  I just did a pull and I am getting new items in Sikulix-2014
but nothing in Sikulix-2.   As you said "-2" isn't ready for use and I respect that.
Other than the nightly build, is there a way I can get the experimental "development" drop via git pull so I can test out what may be coming (and I use it with the understanding that it is alpha)

thanks

**Comment by RaiMan** [comment]
no problem, just do the normal git way:
- make a fork
- get your fork on your local machine
- open the project in some IDE (I am currently switching to IntelliJ IDEA CE from NetBeans)
- run mvn install either from within the IDE or on commandline (needs a Maven install) in the root of the project.
- code that does something is in sikulix2apitest in the src/test branch (running as test)

Since I am currently trying to switch the project to OpenCV 3, you might get problems.
Come back when you arrive there.

**Comment by RaiMan** [comment]
SikuliNG will not have its own IDE GUI
